function M = A_ball(m)
%A_BALL
%    M = A_BALL(M)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Nov-2020 22:18:28

M = reshape([m,0.0,0.0,0.0,m,0.0,0.0,0.0,m],[3,3]);
