function b = b(c,g,m,x_vel,y_vel,z_vel)
%B
%    B = B(C,G,M,X_VEL,Y_VEL,Z_VEL)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Nov-2020 16:09:39

t2 = x_vel.^2;
t3 = y_vel.^2;
t4 = z_vel.^2;
t5 = t2+t3+t4;
t6 = sqrt(t5);
b = [-c.*t6.*x_vel;-c.*t6.*y_vel;-g.*m-c.*t6.*z_vel];
