# Harrison Hidalgo
# ECE 5725 - Final Project

def A_ball(m):
#A_BALL
#    M = A_BALL(m)
#    This function was generated by the Symbolic Math Toolbox version 8.5.
#    23-Nov-2020 22:18:28
	import numpy as np
	M = np.array([[m,0.0,0.0],[0.0,m,0.0],[0.0,0.0,m]])
	return M
