import math
import numpy as np

def b_ball(c,g,m,x_vel,y_vel,z_vel)
%B_BALL
%    B = B_BALL(C,G,M,X_VEL,Y_VEL,Z_VEL)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Nov-2020 22:18:28

t2 = x_vel.^2;
t3 = y_vel.^2;
t4 = z_vel.^2;
t5 = t2+t3+t4;
t6 = math.sqrt(t5);
b = np.matrix('-c.*t6.*x_vel;-c.*t6.*y_vel;-g.*m-c.*t6.*z_vel');
return b
